---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "00-bad-apple-lclp"
  annotations:
    pipelinesascode.tekton.dev/target-namespace: "pac-e2e-ns-s49ln"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
spec:
  pipelineSpec:
    tasks:
      - name: noexist
        runAfter:
          - donotexist
        taskSpec:
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                exit 0
