---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "pipelinerun-pr-number-variable"
  annotations:
    pipelinesascode.tekton.dev/target-namespace: "pac-e2e-ns-jkj77"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/heads/temp-base-branch-jst8g]"
    pipelinesascode.tekton.dev/on-event: "[push]"
spec:
  pipelineSpec:
    tasks:
      - name: task
        displayName: "The Task name is Task"
        taskSpec:
          steps:
            - name: task
              image: registry.access.redhat.com/ubi10/ubi-micro
              command: ["/bin/echo", "I don't know my PR number is {{ pull_request_number }}"]
