---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pac-demo-pull-request-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, incoming]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineSpec:
    tasks:
      - name: task
        displayName: "The Task name is Task"
        taskSpec:
          steps:
            - name: task
              image: registry.access.redhat.com/ubi9/ubi-micro
              command: ["sleep", "2m"]
