---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pac-demo-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: body
      value: "{{ body }}"
  pipelineSpec:
    tasks:
      - name: task
        displayName: "Task"
        taskSpec:
          steps:
            - name: task
              image: registry.access.redhat.com/ubi9/ubi-micro
              command: ["/bin/echo", "$(params.body)"]
