---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "pipelinerun-match-all-branch-trpd"
  annotations:
    pipelinesascode.tekton.dev/target-namespace: "pac-e2e-ns-49gdx"
    pipelinesascode.tekton.dev/on-target-branch: "[*]"
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
spec:
  pipelineSpec:
    tasks:
      - name: task
        displayName: "The Task name is Task"
        taskSpec:
          steps:
            - name: task
              image: registry.access.redhat.com/ubi10/ubi-micro
              command: ["/bin/echo", "HELLOMOTO"]
