---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "pr-gitops-comment"
  annotations:
    pipelinesascode.tekton.dev/target-namespace: "pac-e2e-push-qpdkh"
    pipelinesascode.tekton.dev/on-target-branch: "[pac-e2e-push-qpdkh]"
    pipelinesascode.tekton.dev/on-event: "[push]"
spec:
  pipelineSpec:
    tasks:
      - name: task
        displayName: "The Task name is Task"
        taskSpec:
          steps:
            - name: task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "HELLOMOTO"
                sleep 30
                exit 0
