---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: label-pr-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]" 
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-label: "[bug]"
spec:
  pipelineSpec:
    tasks:
      - name: task
        displayName: "The Task name is Task"
        taskSpec:
          steps:
            - name: task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                sleep 5s
                exit 0
