---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cel-expr-pr-
  annotations:
    # pipelinesascode.tekton.dev/on-event: "[push]"
    # pipelinesascode.tekton.dev/on-target-branch: "[main]"
    # pipelinesascode.tekton.dev/on-label: "[bug]"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
spec:
  pipelineRef:
    name: pipeline-ref
