---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: label-err-pr
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && target_branch == "main" && files.all != ["README.md"]
spec:
  params:
    - name: body
      value: |
        {{ body }}
  pipelineSpec:
    params:
      - name: body
    tasks:
      - name: noop-task
        displayName: Task with no effect
        taskSpec:
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "Labels on PR: {{ body.action }}"
                exit 0
