---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "pipelinerun-pr-cel-expression-izox"
  annotations:
    pipelinesascode.tekton.dev/target-namespace: "pac-e2e-ns-t6cb5"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
spec:
  pipelineSpec:
    tasks:
      - name: task
        displayName: "The Task name is Task"
        taskSpec:
          steps:
            - name: task
              image: registry.access.redhat.com/ubi9/ubi-micro
              command: ["/bin/echo", "HELLOMOTO"]
