---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "pipelinerun-tekton-validation-ojdy"
  annotations:
    pipelinesascode.tekton.dev/target-namespace: "pac-e2e-ns-j84c7"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          stepsos:
            - name: step
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "HELLOMOTO"
                exit 0