---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pr-third
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "git-clone"
    pipelinesascode.tekton.dev/task-1: "golangci-lint"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineSpec:
    tasks:
      - name: task
        displayName: "The Task name is Task"
        taskSpec:
          steps:
            - name: step-1
              image: registry.access.redhat.com/ubi9/ubi-micro
              command: ["sleep", "30s"]
            - name: step-2
              image: registry.access.redhat.com/ubi9/ubi-micro
              command: ["/bin/echo", "I am third PipelineRun"]
