---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "plr-1"
  annotations:
    pipelinesascode.tekton.dev/on-label: "[]"  
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && target_branch == "main" &&
        body.pull_request.labels.exists(l, l.name == "bug")
      
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          steps:
            - name: step-1
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                sleep 1m
                exit 1
