---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: i-wont-match
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/on-label: "[bug, defect]"
spec:
  pipelineSpec:
    tasks:
      - name: task
        displayName: This is a task
        taskSpec:
          steps:
            - name: task-step
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "I am pr"
                exit 0
