---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "fail-plr"
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && body.action == "closed"
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          steps:
            - name: step-1
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                sleep 1s
                exit 0
