---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "plr-1"
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"   
    pipelinesascode.tekton.dev/pipeline: "./pipeline.yaml"
spec:
  pipelineRef:
    name: pipeline
