---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: "plr-2-"
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          steps:
            - name: step-1
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                sleep 10s
                exit 0
