---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "plr-5"
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          steps:
            - name: step-1
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                sleep 20s
                echo "something serious is happening inside me that's why I am failing!"
                exit 1
