---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: simple-push-pr
  annotations:
    # pipelinesascode.tekton.dev/on-comment: "^/(help|(assign|unassign|label|unlabel)[ ].*)"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && target_branch == "main"
    # pipelinesascode.tekton.dev/cancel-in-progress: "true"
spec:
  pipelineSpec:
    tasks:
      - name: task
        displayName: This is a task
        taskSpec:
          steps:
            - name: task-step
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "{{ git_tag }}"
                exit 0  
