---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: prow-commands
  annotations:
    # pipelinesascode.tekton.dev/on-comment: "^/(help|(assign|unassign|label|unlabel)[ ].*)"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-path-change: "[.tekton/prs/*]"
spec:
  pipelineSpec:
    tasks:
      - name: manage-pr
        displayName: Manage PR Assignments & Labels
        taskSpec:
          steps:
            - name: manage-pr
              image: registry.access.redhat.com/ubi9/ubi-micro
              command: ["/bin/echo", "Hello Tekton!"]
