---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "prlongrunnning-6-yobi"
  annotations:
    pipelinesascode.tekton.dev/target-namespace: "pac-e2e-ns-vr2hr"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          steps:
            - name: task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "hello pipeline"
                sleep 20
                exit 0
