---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "push-plr"
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          steps:
            - name: step-1
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "I am push event but from a pull request, pull_request_number: {{ pull_request_number }}"
                exit 0
