---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "label-check-pr"
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && target_branch == "main" &&
        (!has(body.pull_request.labels) || !has(body.pull_request.requested_reviewers))
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          steps:
            - name: step-1
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                sleep 5s
                exit 0
