---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "push-plr"
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: event == "incoming" && target_branch == "main"
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          steps:
            - name: step-1
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "I am an incoming event"
                exit 0
