---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: "tag-push-plr"
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "[refs/tags/*]"
    pipelinesascode.tekton.dev/on-event: "[push]"
spec:
  pipelineSpec:
    tasks:
      - name: task
        taskSpec:
          steps:
            - name: step-1
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "tag {{ git_tag }} is pushed."
                sleep 1m
                exit 0
