---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pull-pr-1
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/tags/*]"
spec:
  params:
    - name: branch
      value: |
        {{ body.pull_request.title.endsWith("23806") ? "branch has number" : "branch doesn't have number" }}
  pipelineSpec:
    tasks:
      - name: task
        displayName: This is a task
        taskSpec:
          steps:
            - name: task-step
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "tag {{ git_tag }} is pushed"
                exit 0
