---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "tag-plr"
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch.matches("refs/tags/.*")
spec:
  pipelineSpec:
    tasks:
      - name: test-task
        taskSpec:
          steps:
            - name: test
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "this was the {{ git_tag }}"
                exit 0
